exports.commands = [
	'List of commands ',
	'\n		 🕵️‍♀️info/text-based🧾',
	'!server - Get some information about the server',
	'!fact - Get a random duck fact',
	'!insult @username- I will insult the tagged user',
	'!lolAdvice - gives useful information on how to climb',
	'!dadJoke - gives you a dad joke',
	'!msgCount - displays how many times each user has issued a successful command, starting from 8:00pm 12/29/2023',
	'\n		🔊Soundboard🔊',
	'!jeff - name jeff  \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t🔑: !jef',
	'!quack - make me quack\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t🔑: !qak',
	'!quadra - QUAAAAAAAAAAADRA KILLLLL\t\t\t\t\t\t\t\t\t\t\t\t\t\t🔑: !quad',
	"!sion - plays one of Sion's 10 various ult sounds",
	'!rl - THIS IS ROCKET LEAGUE!',
	'!bruh',
	'!mana - YOU HAVE NO MANA',
	'!faker - FAKER WHAT WAS THAT\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t🔑: !fkr',
	'!borat - very nice!\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t🔑: !brt ; !vnic',
	'!crickets - cricket sounds\t\t\t\t\t\t\t\t\t\t\t\t🔑: !crk',
	'!gay - why are you gay',
	'!ornn - ORNNNNNNN',
	'!ok - Hi! ...okay',
	'!kys - what you think it is, but dramatic af',
	"!coming = IIIIIIIIIIIIII'm... du, dada doo de du, COmiiiiiin DOO DOO DA DOO 🔑: !cmg",
	"!widePutin - he's here   (＠_＠;)\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t🔑: !wide",
	"!imBack - I'm back baby (1 of 12 variations) \t\t\t\t\t\t\t\t\t\t\t\t\t\t🔑: !bak",
	'!hydration - THE TIME FOR HYDRATIONNNNNNNNN\t\t\t\t\t\t\t\t\t\t🔑: !hyd',
	'!nice - *bass boosted tongue pop* nice',
	'!cum - trump cummin',
	"!thinPutin - he's here.... but thin!  \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t🔑: !thin",
	'!dontcare - as you might expect, dont care\t\t\t\t\t\t\t\t\t\t\t\t\t\t🔑: !dc',
	'!everyone - EVERYONE. GET IN HERE\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t🔑: !ev1',
	'!gragas - IF YOURE BUYING...\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t🔑: !grag',
	'!sadtrombone - Womp womp womp wooooooooooomp\t\t\t\t\t\t\t🔑: !stb',
	'!max - DOO DOO DOO DOO... MAX VERSTAPPEN',
	'!fifty - 50% chance I say something positive to you, 50% chance negative',
	'!speech - You have one minute, make it count',
	'!boss - 10 seconds of intense and dramatic boss music',
	'!sure - are you SURE about that?',
	'!comrade - da theme',
	'!hype - get hype. dodododdododo',
	'!hype2 - a different one',
	'!emotional - 2min24sec to speak about something important and dramatic',
	'!vineboom - the vine boom sound effect 🔑: !vb',
]
