exports.commands = [
	'List of commands ',
	'\n		 🕵️‍♀️info/text-based🧾',
	'!server - Get some information about the server',
	'!fact - Get a random duck fact',
	'!insult @username- I will insult the tagged user',
	'!lolAdvice - gives useful information on how to climb',
	'!dadJoke - gives you a dad joke',
	'!msgCount - displays how many times each user has issued a successful command, starting from 12/29/23 🔑!mc',
	'!msgTypeCount - displays how many times each message has been used, starting from 7/20/24 🔑!mtc',
	'\n		🔊Soundboard🔊',
	'!jeff - name jeff  🔑: !jef',
	'!quack - make me quack 🔑: !qak',
	'!quadra - QUAAAAAAAAAAADRA KILLLLL 🔑: !quad',
	"!sion - plays one of Sion's 10 various ult sounds",
	'!rl - THIS IS ROCKET LEAGUE!',
	'!bruh',
	'!mana - YOU HAVE NO MANA',
	'!faker - FAKER WHAT WAS THAT 🔑: !fkr',
	'!borat - very nice! 🔑: !brt ; !vnic',
	'!gay - why are you gay',
	'!ornn - ORNNNNNNN',
	'!ok - Hi! ...okay',
	'!kys - what you think it is, but dramatic af',
	"!coming = IIIIIIIIIIIIII'm... du, dada doo de du, COmiiiiiin DOO DOO DA DOO 🔑: !cmg",
	"!widePutin - he's here   (＠_＠;) 🔑: !wide",
	"!imBack - I'm back baby (1 of 12 variations) 🔑: !bak",
	'!hydration - THE TIME FOR HYDRATIONNNNNNNNN 🔑: !hyd',
	'!nice - *bass boosted tongue pop* nice',
	'!cum - trump cummin',
	"!thinPutin - he's here.... but thin! 🔑: !thin",
	'!dontcare - as you might expect, dont care 🔑: !dc',
	'!everyone - EVERYONE. GET IN HERE 🔑: !ev1',
	'!gragas - IF YOURE BUYING... 🔑: !grag',
	'!sadtrombone - Womp womp womp wooooooooooomp\t\t\t\t\t\t\t🔑: !stb',
	'!max - MAX VERSTAPPEN',
	'!fifty - 50% chance I say something positive to you, 50% chance negative',
	'!speech - You have one minute, make it count',
	'!boss - 10 seconds of intense and dramatic boss music',
	'!sure - are you SURE about that?',
	'!comrade - da theme',
	'!hype - get hype',
	'!hype2 - more hype',
	'!emotional - 2min24sec to speak about something important and dramatic',
	'!vineboom - the vine boom sound effect 🔑: !vb',
	'!bye - bye! have a great time!',
]
