exports.commands = [
	'!help - List commands and their description',
	'!server - Get some information about the server',
	'!fact - Get a random duck fact',
	'!insult @username- I will insult the tagged user',
	'!jeff - name jeff',
	'!lolAdvice - gives useful information on how to climb',
	'!quack - make me quack',
	'!phreak - quadra kill?',
	"!sion - plays one of Sion's various ult sounds",
	'!rl - This is rocket league',
	'!bruh - bruh',
	'!mana - YOU HAVE NO MANA',
	'!faker - FAKER WHAT WAS THAT',
	'!borat - very nice!',
	'!dadJoke - I will tell you a random dad joke',
]
