const facts = [
    'The word duck comes from the Old English word that means diver. They have strong, scaled legs that are set far back on the body, and strong wings that are usually quite short and come to a point.',
    'Dabbling ducks have a pecten, a comb-like structure along the edge of the beak that allows them to strain water and trap food.',
    'Ducks can feed on water or land but when in the water, they will dive as deep as they can without being submerged in order to trap food in their beak.',
    'Ducks eat a variety of food, including grasses, aquatic plants, fish, insects, small amphibians, worms and small molluscs.',
    'Ducks tend to mate with only one other duck but the relationships generally only last a single year. Just like Riley.',
    'Ducks will usually make a nest before breeding. After their young hatch, they will lead them to water.',
    'While mother ducks are protective, they will abandon a duckling if it is physically stuck or is sick. A duckling might also be abandoned if it hatches too late and the mother has already led its siblings to water.',
    'Most species of ducks do not make the commonly known quacking sound. Ducks use a wide range of calls, including whistles, cooing, yodels and even grunts.',
    'Ducks have many predators. Ducklings are incredibly vulnerable, mostly because they are unable to fly. A duck’s ability to flee the scene of danger is one of its best defense mechanisms.',
    'Some of the duck’s predators include large fish, and even larger birds, like herons. A duck’s nest may be raided by land dwelling predators, including foxes or hawks.',
    'Ducks are farmed all over the world, usually for their meat and eggs. But they are also farmed for their feathers, which are commonly used in bedding and pillows.',
    'China has the largest market for duck in the world. Several different species of duck are eaten throughout the world, and duck is often considered a higher class of meat in America than chicken or turkey.',
    'Ducks have special webbed feet that do more than just help them swim. Their feet have a complex structure of capillaries, which help to regulate blood flow and keep their feet warm, even in freezing waters. However, their webbed feet mean that they have difficulty walking on land and this is where they get their familiar waddle motion from.',
    'Like most other types of birds, ducks don’t have teeth. Instead, they have rows of thin bristles in their mouths that help them filter nutrient particles out of the water that passes through their breaks.',
    'When a duck catches larger items of food, it swallows them whole and uses its gizzard to help digest the food.',
    'While a duck\'s beak is of course mostly for catching food, they also use it to pick dirt and other types of debris out of their feathers.',
    'One of the more commonly known duck facts is that the birds usually migrate. They leave for several reasons, but usually to escape harsh weather in order to be able to eat and breed. ',
    'Ducks know that it is time to migrate when the fall season starts and the days become shorter. US ducks will travel to the southern states, Central America, the Caribbean and Mexico. As the days become longer and hotter in the south, the ducks will tend to head back north.',
    'Ducks have been a part of pop culture for many years. The two most famous fictional ducks are Disney’s Donald Duck, who was introduced in 1934, and Warner Bros.’ Daffy Duck, who was introduced in 1937.',
    'Ducks have two regular eyelids, just like humans, that blink open and closed. But they also have a third eyelid that is located on the side of the eye. These close across the eyes, and act as a pair of goggles, allowing the bird to keep its eyes open without getting water in them.',
    'It is said that ducks are very social animals and should not be kept alone. If a duck does not have any other ducks nearby, it will actually take on the persona of who it is with.',
    'According to the Guinness Book Of World Records, the oldest duck was named Desi Duck and lived in Maidenhead, England. She was a mallard duck and lived to be 20 years, 3 months and 16 days old. She died in August of 2002 and was owned by Ingrid Raphael.',
    'Most ducks live for 4 to 8 years in the wild. If they don’t die from old age, they are usually killed by predators, hunters or by loss of habitat and dangers from pollution, like plastic bags and rings.',
    'Mallard ducks, along with several other species, shed all of their flight feathers at the end of the breeding season. This leaves them unable to fly for up to a full month.',
    'Ducks can fly at surprising speeds. Mallards can fly at up to 55 miles per hour, while other species can hit top speeds of 88 miles per hour.',
    'Ducks are able to sleep with one eye open! Ducks usually sleep side by side in a long row, and scientists have found that the ducks at the end of the row will actually sleep with one eye open, specifically the one that is facing away from the row.',
    'Ducks are able to control which side of their brain stays awake, letting them rest but also keep an eye out for predators and other dangers.',
    'A baby duck is called a duckling, a male is a drake and a female is a hen or duck.',
    'A group of ducks is called a raft, a team or a paddling. Generic “bird” terms can also be used like chick, bird or flock.',
    'Ducks have highly waterproof feathers thanks to an intricate feather pattern and a wax like coating that they spread onto their feathers while preening. Duck feathers are so waterproof that they can dive completely underwater and the downy under-feathers will stay totally dry.',
    'Ducks live in both fresh water and sea water and can be found on every continent except for Antarctica',
    'Ducks have a special counter current blood vessel system in their feet/legs so their feet will not feel cold.',
    'Most bird species have a “sequential molt” where they lose their flight feathers one at a time, allowing them to always have the ability to fly.',
    'Drakes unfortunately have a reputation of very aggressive mating that can sometimes even result in injury or death.  In some species of ducks, a female will bond with a male for one season – but she will still be harassed into mating by other males.  The female can protect herself from insemination from an unwanted male with a long, complicated oviduct full of twists, turns & chambers.  She can sideline sperm & eject it later, so that she only reproduces with the male of her choosing.',
    'Drakes are one of the few bird species that have an external phallus. It is a long, corkscrew shaped tentacle that retracts into their body when not mating – sometimes they can grow to be as long as their entire body!',
    'For the Drake, in the fall their phallus completely falls off, only to regrow in the spring.  Scientists are unsure why this happens, but think it might be because it is easier to grow a new one rather than keep it healthy.',
    'Ducks can change genders – Gender change in ducks is rare, but happens as often as 1 in every 10,000 birds and can happen both from female to male and male to female, although female to male seems much more common.',
    'Ducks turn white with age. White ducks are white their whole lives, but dark-colored ducks slowly develop white patches in their feathers as they age, just like humans. Eventually, when they are very old, they could become entirely white.'
];

exports.getRandomFact = () => {
    return facts[Math.floor(Math.random() * facts.length)];
};